parsing ok, pas de leak, debut mlx

diff --git a/libft/Makefile b/libft/Makefile
--- a/libft/Makefile
+++ b/libft/Makefile
@@ -6,19 +6,27 @@
 #    By: grenaud- <grenaud-@student.42.fr>          +#+  +:+       +#+         #
 #                                                 +#+#+#+#+#+   +#+            #
 #    Created: 2021/11/01 15:33:28 by grenaud-          #+#    #+#              #
-#    Updated: 2023/04/05 12:25:30 by grenaud-         ###   ########.fr        #
+#    Updated: 2023/04/06 17:35:07 by grenaud-         ###   ########.fr        #
 #                                                                              #
 # **************************************************************************** #
 
-Y = "\033[33m"
-R = "\033[31m"
-G = \033[32m
-B = "\033[34m"
-X = "\033[0m"
-UP = "\033[A"
-CUT = "\033[K"
-REVR = \033[7m
-BOLD = "\033[1m"
+Y 			= "\033[33m"
+R 			= "\033[31m"
+G 			= \033[32m
+B 			= "\033[34m"
+X 			= "\033[0m"
+UP 			= "\033[A"
+CUT 		= "\033[K"
+REVR		= \033[7m
+BOLD 		= "\033[1m"
+COM_COLOR   = \033[0;34m
+OBJ_COLOR   = \033[0;36m
+OK_COLOR    = \033[0;32m
+ERROR_COLOR = \033[0;31m
+WARN_COLOR  = \033[0;33m
+NO_COLOR    = \033[m
+
+NOVISU 		= 0 # 1 = no progress bar usefull when tty is not available
 
 SRC_DIR		=	./
 
@@ -91,21 +99,149 @@ CC            = gcc
 CFLAGS        = -Wall -Wextra -Werror
 
 AR_RCS        = ar rcs
+define run_and_test
+printf "%b%-46b" "$(COM_COLOR)$(COM_STRING) " "$(OBJ_COLOR)$(@F)$(NO_COLOR)"; \
+$(RUN_CMD); \
+if [ $$RESULT -ne 0 ]; then \
+	printf "%b\n" "$(ERROR_COLOR)[✖]$(NO_COLOR)"; \
+	rm -rf .files_changed; \
+	if [ $(NOVISU) -eq 0 ]; then \
+		echo; \
+	fi; \
+elif [ -s $@.log ]; then \
+	printf "%b\n" "$(WARN_COLOR)[⚠]$(NO_COLOR)"; \
+else  \
+	printf "%b\n" "$(OK_COLOR)[✓]$(NO_COLOR)"; \
+fi; \
+cat $@.log; \
+rm -f $@.log; \
+exit $$RESULT
+endef
+
+define save_files_changed
+	FILE_CPP=`echo $(SRCS) $(MAIN)`; \
+	FILE_OBJ=`find objs -type f -name '*.o' 2>/dev/null | sed 's/objs\///'`; \
+	TO_COMPILE=`echo $$FILE_CPP | wc -w`; \
+	for FILE in $$FILE_CPP; do \
+		for OBJ in $$FILE_OBJ; do \
+			if [ $${FILE%$(FILE_EXTENSION)} = $${OBJ%.o} ]; then \
+				if [ $(SRCS_PATH)/$$FILE -ot objs/$$OBJ ]; then \
+					FILE_DEP=`echo objs/$$OBJ | sed 's/\.o/\.d/'`; \
+					HEAD_FILES=`< $$FILE_DEP xargs | grep -oh "\w*.h\w*"`; \
+					RECOMPILE=0; \
+					for HEAD in $$HEAD_FILES; do \
+						if [ $(SRCS_PATH)/$$HEAD -nt objs/$$OBJ ]; then \
+							RECOMPILE=1; \
+							break; \
+						fi; \
+					done; \
+					if [ $$RECOMPILE -eq 0 ]; then \
+						((TO_COMPILE=$$TO_COMPILE-1)); \
+					fi;\
+				fi; \
+			fi; \
+		done; \
+	done; \
+	echo 0/$$TO_COMPILE > .files_changed
+endef
+
+define draw_bar
+	FILE_TOTAL=`bash -c 'cat .files_changed | cut -d"/" -f2'`; \
+	FILE_DONE=`bash -c 'cat .files_changed | cut -d"/" -f1'`; \
+	if [ $$FILE_TOTAL -eq 0 ]; then \
+		FILE_TOTAL=1; \
+		FILE_DONE=1; \
+	fi; \
+	RES=`echo "scale=2; $$FILE_DONE/$$FILE_TOTAL*48" | bc`; \
+	RES=`echo $${RES%%.*}`; \
+	printf "$(OBJ_COLOR)[$(NO_COLOR)"; \
+	i=0; \
+	while [ $$i -lt 48 ]; do \
+		if [ $$i -lt $$RES ]; then \
+			printf "$(OK_COLOR)█$(NO_COLOR)"; \
+		else \
+			printf "$(COM_COLOR)▒$(NO_COLOR)"; \
+		fi; \
+		((i=$$i+1)); \
+	done; \
+	printf "$(OBJ_COLOR)]$(NO_COLOR)"; \
+	printf " ($(COM_COLOR)$$FILE_DONE$(NO_COLOR)/$(COM_COLOR)$$FILE_TOTAL$(NO_COLOR))"; \
+	printf " "; \
+	((FILE_DONE=$$FILE_DONE+1)); \
+	echo $$FILE_DONE/$$FILE_TOTAL > .files_changed;
+endef
+
+define draw_bar
+	FILE_TOTAL=`bash -c 'cat .files_changed | cut -d"/" -f2'`; \
+	FILE_DONE=`bash -c 'cat .files_changed | cut -d"/" -f1'`; \
+	if [ $$FILE_TOTAL -eq 0 ]; then \
+		FILE_TOTAL=1; \
+		FILE_DONE=1; \
+	fi; \
+	RES=`echo "scale=2; $$FILE_DONE/$$FILE_TOTAL*48" | bc`; \
+	RES=`echo $${RES%%.*}`; \
+	printf "$(OBJ_COLOR)[$(NO_COLOR)"; \
+	i=0; \
+	while [ $$i -lt 48 ]; do \
+		if [ $$i -lt $$RES ]; then \
+			printf "$(OK_COLOR)█$(NO_COLOR)"; \
+		else \
+			printf "$(COM_COLOR)▒$(NO_COLOR)"; \
+		fi; \
+		((i=$$i+1)); \
+	done; \
+	printf "$(OBJ_COLOR)]$(NO_COLOR)"; \
+	printf " ($(COM_COLOR)$$FILE_DONE$(NO_COLOR)/$(COM_COLOR)$$FILE_TOTAL$(NO_COLOR))"; \
+	printf " "; \
+	((FILE_DONE=$$FILE_DONE+1)); \
+	echo $$FILE_DONE/$$FILE_TOTAL > .files_changed;
+endef
+
+define display_progress_bar
+	if [ $(NOVISU) -eq 0 ]; then \
+		line=`bash -c 'oldstty=$$(stty -g); stty raw -echo min 0; tput u7 > /dev/tty; IFS=";" read -r -d R -a pos; stty $$oldstty; row=$$(($${pos[0]:2} - 1)); echo $$row'`; \
+		max_line=`tput lines`; \
+		((max_line=$$max_line-2));\
+		new_line=0; \
+		tput sc; \
+		i=0; \
+		while [ $$i -lt 60 ]; do \
+			printf " "; \
+			((i=$$i+1)); \
+		done; \
+		tput rc; \
+		if [ $$line -gt $$max_line ]; then \
+			new_line=1; \
+			echo ; \
+		else \
+			((line=$$line+1));\
+		fi; \
+		tput sc; \
+		tput cup $$line; \
+		$(draw_bar) \
+		if [ $$new_line -eq 1 ]; then \
+			((line=$$line-1));\
+			tput cup $$line; \
+		else \
+			tput rc; \
+		fi; \
+	fi
+endef
 
 all:            ${NAME}
 
 .c.o:
 				@${CC} ${CFLAGS} -c $< -o ${<:.c=.o}
-				@printf "$(G) $(REVR) " $(X)
+				@printf "$(G) $(REVR)" $(X)
 
 ${NAME}:        ${OBJS}
-				@echo $(BOLD)[libft compiled]$(BOLD)
+				@echo $(BOLD)[libft compiled][✓]$(BOLD)
 				@${AR_RCS} ${NAME} ${OBJS}
 
 bonus:			${BONUS_OBJS}
 				@${AR_RCS} ${NAME} ${BONUS_OBJS}
 
-clean:
+clean:			
 				@rm -f ${OBJS} ${BONUS_OBJS}
 
 fclean:			clean
